import React, { useState } from 'react';
import {
  Receipt,
  Plus,
  Printer,
  Search,
  Trash2,
  Wand2,
  Calendar,
  CheckCircle,
  HelpCircle,
  Sparkles,
  Layers,
  Users,
  Building,
  X
} from 'lucide-react';
import { KwitansiDocument, SchoolMasterData, ProjectProgressWeek } from '../types';
import { formatRupiah } from '../utils/formatters';
import { terbilangRupiah } from '../utils/terbilang';

interface KwitansiManagerProps {
  kwitansiList: KwitansiDocument[];
  school: SchoolMasterData;
  progressWeeks?: ProjectProgressWeek[];
  onOpenPrintKwitansi: (kwitansiId: string, docMode: 'ALL' | 'KWITANSI' | 'FAKTUR' | 'SPB') => void;
  onAddNewKwitansi: () => void;
  onDeleteKwitansi: (id: string) => void;
  onAutoGenerateDailyAndWeekly?: (selectedWeekNums: number[], splitDays: boolean) => void;
}

export const KwitansiManager: React.FC<KwitansiManagerProps> = ({
  kwitansiList,
  school,
  progressWeeks = [],
  onOpenPrintKwitansi,
  onAddNewKwitansi,
  onDeleteKwitansi,
  onAutoGenerateDailyAndWeekly,
}) => {
  const [activeType, setActiveType] = useState<string>('ALL');
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedKw, setSelectedKw] = useState<KwitansiDocument | null>(kwitansiList[0] || null);

  // Auto Generator Modal State
  const [isGeneratorModalOpen, setIsGeneratorModalOpen] = useState(false);
  const [selectedWeeksForGen, setSelectedWeeksForGen] = useState<number[]>([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]);
  const [enableDailySplit, setEnableDailySplit] = useState(true);
  const [genSuccessMsg, setGenSuccessMsg] = useState<string | null>(null);

  const filtered = kwitansiList.filter((k) => {
    const matchType = activeType === 'ALL' || k.tipe === activeType;
    const matchSearch =
      k.noBukti.toLowerCase().includes(searchQuery.toLowerCase()) ||
      k.uraian.toLowerCase().includes(searchQuery.toLowerCase()) ||
      (k.namaToko && k.namaToko.toLowerCase().includes(searchQuery.toLowerCase())) ||
      k.penerimaNama.toLowerCase().includes(searchQuery.toLowerCase());
    return matchType && matchSearch;
  });

  const handleToggleWeek = (num: number) => {
    setSelectedWeeksForGen((prev) =>
      prev.includes(num) ? prev.filter((w) => w !== num) : [...prev, num].sort((a, b) => a - b)
    );
  };

  const handleSelectAllWeeks = () => {
    setSelectedWeeksForGen([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]);
  };

  const handleRunAutoGenerator = () => {
    if (selectedWeeksForGen.length === 0) {
      alert('Pilih minimal 1 minggu untuk digenerate kwitansinya.');
      return;
    }
    if (onAutoGenerateDailyAndWeekly) {
      onAutoGenerateDailyAndWeekly(selectedWeeksForGen, enableDailySplit);
      setGenSuccessMsg(
        `Berhasil meng-generate kwitansi pembelian bahan harian dan upah mingguan untuk ${selectedWeeksForGen.length} minggu berdasarkan bobot progres fisik Laporan Mingguan!`
      );
      setIsGeneratorModalOpen(false);
      setTimeout(() => setGenSuccessMsg(null), 6000);
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-xs flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-blue-100 text-blue-800 uppercase">
              Otomatisasi SPJ Kuitansi & SPB
            </span>
            <span className="text-xs text-slate-500">Sesuai Bobot Progres Fisik Laporan Mingguan</span>
          </div>
          <h2 className="text-lg font-bold text-slate-900 flex items-center gap-2">
            <Receipt className="w-5 h-5 text-blue-600" />
            <span>Kwitansi Pembayaran, Bon/Faktur Toko & Surat Pesanan Barang (SPB)</span>
          </h2>
          <p className="text-xs text-slate-500 mt-1 max-w-2xl">
            Setiap kwitansi terhubung langsung dengan Surat Pesanan Barang (SPB), Bon Faktur Toko, dan Buku Kas Umum (BKU). Anda dapat memecah pembelian bahan harian dan upah mingguan sesuai progres fisik.
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          {onAutoGenerateDailyAndWeekly && (
            <button
              type="button"
              onClick={() => setIsGeneratorModalOpen(true)}
              className="flex items-center gap-1.5 bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-700 hover:to-purple-700 text-white px-4 py-2 rounded-xl text-xs font-bold shadow-md shadow-indigo-500/20 transition cursor-pointer"
            >
              <Wand2 className="w-4 h-4 text-purple-200" />
              <span>Auto-Generate Kwitansi Harian & Upah</span>
            </button>
          )}

          <button
            type="button"
            onClick={onAddNewKwitansi}
            className="flex items-center gap-1.5 bg-blue-600 hover:bg-blue-700 text-white px-3.5 py-2 rounded-xl text-xs font-semibold shadow-xs transition cursor-pointer"
          >
            <Plus className="w-4 h-4" />
            <span>+ Buat Manual</span>
          </button>
        </div>
      </div>

      {/* Success Banner */}
      {genSuccessMsg && (
        <div className="bg-emerald-50 border border-emerald-300 text-emerald-900 px-5 py-3.5 rounded-xl flex items-center justify-between shadow-xs animate-in fade-in">
          <div className="flex items-center gap-3">
            <CheckCircle className="w-5 h-5 text-emerald-600 shrink-0" />
            <p className="text-xs font-bold">{genSuccessMsg}</p>
          </div>
          <button
            type="button"
            onClick={() => setGenSuccessMsg(null)}
            className="text-xs text-emerald-800 font-semibold underline cursor-pointer"
          >
            Tutup
          </button>
        </div>
      )}

      {/* Auto Generator Modal */}
      {isGeneratorModalOpen && (
        <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-xs flex items-center justify-center p-4 z-50 animate-in fade-in">
          <div className="bg-white rounded-2xl shadow-2xl border border-slate-200 max-w-xl w-full p-6 space-y-5">
            <div className="flex items-center justify-between border-b pb-3">
              <div className="flex items-center gap-2">
                <div className="p-2 bg-purple-100 rounded-lg text-purple-700">
                  <Wand2 className="w-5 h-5" />
                </div>
                <div>
                  <h3 className="font-extrabold text-sm text-slate-900">
                    Generator Kwitansi Harian & Upah Mingguan
                  </h3>
                  <p className="text-xs text-slate-500">
                    Sistem akan memecah pembelian barang harian dan upah sesuai bobot Laporan Mingguan.
                  </p>
                </div>
              </div>
              <button
                type="button"
                onClick={() => setIsGeneratorModalOpen(false)}
                className="text-slate-400 hover:text-slate-600"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* Options */}
            <div className="space-y-4 text-xs">
              <div className="bg-purple-50/70 border border-purple-200 p-3.5 rounded-xl space-y-2">
                <div className="flex items-center justify-between">
                  <span className="font-bold text-purple-900">1. Pilih Minggu Pekerjaan:</span>
                  <button
                    type="button"
                    onClick={handleSelectAllWeeks}
                    className="text-[11px] font-bold text-purple-700 hover:underline"
                  >
                    Pilih Semua Minggu (1 - 12)
                  </button>
                </div>
                <div className="grid grid-cols-6 gap-1.5 pt-1">
                  {[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12].map((num) => {
                    const isSelected = selectedWeeksForGen.includes(num);
                    return (
                      <button
                        key={num}
                        type="button"
                        onClick={() => handleToggleWeek(num)}
                        className={`py-1.5 px-1 rounded font-bold text-center border transition ${
                          isSelected
                            ? 'bg-purple-600 text-white border-purple-600'
                            : 'bg-white text-slate-700 border-slate-300 hover:bg-slate-100'
                        }`}
                      >
                        M-{num}
                      </button>
                    );
                  })}
                </div>
              </div>

              {/* Toggle Daily Split */}
              <div className="bg-slate-50 border border-slate-200 p-3.5 rounded-xl flex items-start gap-3">
                <input
                  type="checkbox"
                  id="enableDailySplit"
                  checked={enableDailySplit}
                  onChange={(e) => setEnableDailySplit(e.target.checked)}
                  className="mt-0.5 rounded border-slate-300 text-purple-600 focus:ring-purple-500 cursor-pointer"
                />
                <label htmlFor="enableDailySplit" className="cursor-pointer space-y-0.5">
                  <span className="font-bold text-slate-800 block">
                    Pecah Pembelian Bahan Ke Hari Kerja Harian (Senin, Rabu, Jumat)
                  </span>
                  <p className="text-[11px] text-slate-500 leading-normal">
                    Membagi nilai pembelian bahan mingguan menjadi kwitansi harian di tanggal kerja aktif (misal Senin, Rabu, Jumat) agar riwayat BKU & Bon Toko tampak alami dan realistis.
                  </p>
                </label>
              </div>

              {/* Wage Calculation Rules */}
              <div className="bg-slate-50 border border-slate-200 p-3.5 rounded-xl space-y-1.5">
                <span className="font-bold text-slate-800 block">2. Perhitungan Upah & Honor Sesuai Bobot:</span>
                <ul className="text-[11px] text-slate-600 space-y-1 list-disc pl-4">
                  <li><strong>Upah Tukang & Pekerja</strong>: Dihitung mingguan pada hari Sabtu berdasarkan % progres prestasi fisik minggu berjalan.</li>
                  <li><strong>Honor Perencana & Pengawas</strong>: Dihitung proporsional dari porsi Divisi I (Manajemen/Persiapan).</li>
                  <li><strong>Honor Administrasi / Tim P2SP</strong>: Dicairkan bersamaan dengan rekap upah mingguan.</li>
                </ul>
              </div>
            </div>

            <div className="flex justify-end gap-2 pt-2 border-t">
              <button
                type="button"
                onClick={() => setIsGeneratorModalOpen(false)}
                className="px-4 py-2 border border-slate-300 rounded-xl text-xs font-semibold hover:bg-slate-100"
              >
                Batal
              </button>
              <button
                type="button"
                onClick={handleRunAutoGenerator}
                className="flex items-center gap-1.5 bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-700 hover:to-indigo-700 text-white px-5 py-2 rounded-xl text-xs font-bold shadow-md cursor-pointer"
              >
                <Wand2 className="w-4 h-4" />
                <span>Jalankan Auto-Generator</span>
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Filter Tabs & Search */}
      <div className="bg-white p-4 rounded-2xl border border-slate-200 shadow-xs flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <div className="flex flex-wrap gap-1.5">
          {[
            { id: 'ALL', label: 'Semua Kwitansi' },
            { id: 'MATERIAL', label: 'Bahan Bangunan (Toko)' },
            { id: 'UPAH', label: 'Upah Tukang / HOK' },
            { id: 'KONSULTAN', label: 'Jasa Konsultan' },
            { id: 'PERABOT', label: 'Perabot Sekolah' },
            { id: 'OPERASIONAL', label: 'Persiapan & Adm' },
          ].map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveType(tab.id)}
              className={`px-3 py-1.5 rounded-lg text-xs font-medium transition cursor-pointer ${
                activeType === tab.id
                  ? 'bg-blue-600 text-white shadow-xs font-semibold'
                  : 'bg-slate-100 text-slate-600 hover:bg-slate-200'
              }`}
            >
              {tab.label}
            </button>
          ))}
        </div>

        <div className="relative min-w-[200px]">
          <Search className="w-3.5 h-3.5 absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
          <input
            type="text"
            placeholder="Cari kwitansi / toko / nama..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full pl-8 pr-3 py-1.5 text-xs border border-slate-200 rounded-lg focus:outline-hidden focus:ring-2 focus:ring-blue-500"
          />
        </div>
      </div>

      {/* Main Content: Left List, Right Detailed Preview */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left Column: Kwitansi List */}
        <div className="lg:col-span-6 bg-white rounded-2xl border border-slate-200 shadow-xs overflow-hidden flex flex-col max-h-[700px]">
          <div className="p-3.5 bg-slate-50 border-b border-slate-200 flex items-center justify-between text-xs font-bold text-slate-700">
            <span>Daftar Kwitansi ({filtered.length} Dokumen)</span>
            <span className="text-[11px] text-slate-500">Klik untuk lihat rincian & cetak</span>
          </div>

          <div className="overflow-y-auto divide-y divide-slate-100 flex-1">
            {filtered.map((kw) => {
              const isSelected = selectedKw?.id === kw.id;
              return (
                <div
                  key={kw.id}
                  onClick={() => setSelectedKw(kw)}
                  className={`p-3.5 cursor-pointer transition flex items-start justify-between gap-3 ${
                    isSelected ? 'bg-blue-50/90 border-l-4 border-l-blue-600' : 'hover:bg-slate-50'
                  }`}
                >
                  <div className="space-y-1 flex-1 min-w-0">
                    <div className="flex items-center gap-2">
                      <span className="px-2 py-0.5 rounded bg-slate-200 text-slate-800 font-mono font-bold text-[11px]">
                        {kw.noBukti}
                      </span>
                      <span className="text-[11px] text-slate-500">{kw.tanggal}</span>
                      <span className="text-[10px] px-1.5 py-0.5 rounded bg-blue-100 text-blue-800 font-medium">
                        {kw.tipe}
                      </span>
                    </div>
                    <p className="text-xs font-semibold text-slate-900 truncate">
                      {kw.namaToko ? `Toko: ${kw.namaToko}` : kw.penerimaNama}
                    </p>
                    <p className="text-[11px] text-slate-600 line-clamp-1">{kw.uraian}</p>
                  </div>

                  <div className="text-right whitespace-nowrap">
                    <p className="text-xs font-bold text-slate-900 font-mono">{formatRupiah(kw.nominal)}</p>
                    {kw.isPpn && (
                      <span className="text-[9px] bg-amber-100 text-amber-800 px-1 rounded font-medium">
                        PPN 11%
                      </span>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Right Column: Active Document Viewer & Print Trigger */}
        <div className="lg:col-span-6 bg-white rounded-2xl border border-slate-200 shadow-xs p-6 space-y-4">
          {selectedKw ? (
            <div className="space-y-4">
              <div className="flex items-center justify-between border-b border-slate-100 pb-3">
                <div>
                  <div className="flex items-center gap-2">
                    <span className="text-xs font-bold text-blue-600 font-mono">No. {selectedKw.noBukti}</span>
                    {selectedKw.noSpb && (
                      <span className="text-xs text-slate-500 font-mono">| SPB: {selectedKw.noSpb}</span>
                    )}
                  </div>
                  <h3 className="text-base font-bold text-slate-900 mt-0.5">
                    {selectedKw.namaToko || selectedKw.penerimaNama}
                  </h3>
                </div>

                <div className="flex items-center gap-1.5">
                  <button
                    onClick={() => onOpenPrintKwitansi(selectedKw.id, 'ALL')}
                    className="flex items-center gap-1 bg-emerald-600 hover:bg-emerald-700 text-white px-3 py-1.5 rounded-lg text-xs font-semibold shadow-xs cursor-pointer"
                  >
                    <Printer className="w-3.5 h-3.5" />
                    <span>Cetak Set Lengkap</span>
                  </button>
                  <button
                    onClick={() => onDeleteKwitansi(selectedKw.id)}
                    className="p-1.5 text-slate-400 hover:text-rose-600 rounded hover:bg-rose-50 cursor-pointer"
                    title="Hapus kwitansi"
                  >
                    <Trash2 className="w-4 h-4" />
                  </button>
                </div>
              </div>

              {/* Quick Print Tab buttons for this specific receipt */}
              <div className="flex items-center gap-2 p-2 bg-slate-50 rounded-lg border border-slate-100">
                <span className="text-[11px] font-semibold text-slate-600 mr-1">Cetak Dokumen:</span>
                <button
                  onClick={() => onOpenPrintKwitansi(selectedKw.id, 'KWITANSI')}
                  className="px-2.5 py-1 bg-white hover:bg-slate-100 border border-slate-200 rounded text-[11px] font-medium text-slate-700 shadow-2xs"
                >
                  📄 Kwitansi
                </button>
                {selectedKw.namaToko && (
                  <button
                    onClick={() => onOpenPrintKwitansi(selectedKw.id, 'FAKTUR')}
                    className="px-2.5 py-1 bg-white hover:bg-slate-100 border border-slate-200 rounded text-[11px] font-medium text-slate-700 shadow-2xs"
                  >
                    🛒 Faktur / Bon Toko
                  </button>
                )}
                {selectedKw.noSpb && (
                  <button
                    onClick={() => onOpenPrintKwitansi(selectedKw.id, 'SPB')}
                    className="px-2.5 py-1 bg-white hover:bg-slate-100 border border-slate-200 rounded text-[11px] font-medium text-slate-700 shadow-2xs"
                  >
                    📋 Surat Pesanan Barang (SPB)
                  </button>
                )}
              </div>

              {/* Kwitansi Simulation Card */}
              <div className="border border-slate-300 rounded-xl p-5 bg-amber-50/20 font-serif space-y-3 text-xs shadow-2xs">
                <div className="flex justify-between border-b border-slate-200 pb-2">
                  <div className="space-y-0.5">
                    <p className="font-mono text-[11px]">No. : <strong>{selectedKw.noBukti}</strong></p>
                    <p className="font-mono text-[11px]">Tahun : <strong>{school.tahunAnggaran}</strong></p>
                  </div>
                  <div className="text-right">
                    <h4 className="text-base font-bold tracking-widest uppercase underline text-slate-900">KWITANSI</h4>
                  </div>
                </div>

                <div className="space-y-2 py-1">
                  <div className="grid grid-cols-4 gap-2">
                    <span className="text-slate-600">Sudah terima dari:</span>
                    <span className="col-span-3 font-semibold text-slate-900">
                      Bendahara {school.namaSekolah}
                    </span>
                  </div>

                  <div className="grid grid-cols-4 gap-2">
                    <span className="text-slate-600">Uang Banyaknya:</span>
                    <span className="col-span-3 font-bold text-slate-900 italic bg-amber-100/50 p-1.5 rounded border border-amber-200/50">
                      {terbilangRupiah(selectedKw.nominal)}
                    </span>
                  </div>

                  <div className="grid grid-cols-4 gap-2">
                    <span className="text-slate-600">Yaitu:</span>
                    <span className="col-span-3 text-slate-800 leading-relaxed">
                      {selectedKw.uraian}
                    </span>
                  </div>
                </div>

                {/* Items in Kwitansi */}
                {selectedKw.items && selectedKw.items.length > 0 && (
                  <div className="mt-3 border-t border-slate-200 pt-3">
                    <p className="font-sans font-bold text-[11px] text-slate-700 mb-1.5">Rincian Barang / Layanan Terlampir:</p>
                    <table className="w-full text-left font-sans text-[11px] border-collapse">
                      <thead>
                        <tr className="bg-slate-100 border-b border-slate-200">
                          <th className="py-1 px-2">Banyaknya</th>
                          <th className="py-1 px-2">Nama Barang</th>
                          <th className="py-1 px-2 text-right">Harga Satuan</th>
                          <th className="py-1 px-2 text-right">Jumlah</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-slate-100">
                        {selectedKw.items.map((it, idx) => (
                          <tr key={idx}>
                            <td className="py-1 px-2">{it.volume} {it.satuan}</td>
                            <td className="py-1 px-2 font-medium">{it.namaBarang}</td>
                            <td className="py-1 px-2 text-right font-mono">{formatRupiah(it.hargaSatuan, false)}</td>
                            <td className="py-1 px-2 text-right font-mono font-bold">{formatRupiah(it.jumlah, false)}</td>
                          </tr>
                        ))}
                      </tbody>
                      <tfoot>
                        <tr className="border-t border-slate-200 font-bold">
                          <td colSpan={3} className="py-1 px-2 text-right">Total:</td>
                          <td className="py-1 px-2 text-right font-mono text-blue-700">{formatRupiah(selectedKw.nominal)}</td>
                        </tr>
                      </tfoot>
                    </table>
                  </div>
                )}

                {/* Signatures preview */}
                <div className="grid grid-cols-2 gap-4 pt-4 border-t border-slate-200 text-center font-sans text-[11px]">
                  <div>
                    <p className="text-slate-500">Setuju dibayar,</p>
                    <p className="font-semibold text-slate-800">Kepala Sekolah</p>
                    <div className="h-10" />
                    <p className="font-bold underline text-slate-900">{school.namaKepalaSekolah}</p>
                    <p className="text-[10px] text-slate-500">NIP. {school.nipKepalaSekolah}</p>
                  </div>
                  <div>
                    <p className="text-slate-500">{school.kabKota}, {selectedKw.tanggalFormatted}</p>
                    <p className="font-semibold text-slate-800">Yang Menerima,</p>
                    <div className="h-10" />
                    <p className="font-bold underline text-slate-900">{selectedKw.penerimaNama}</p>
                    <p className="text-[10px] text-slate-500">{selectedKw.penerimaPekerjaan}</p>
                  </div>
                </div>
              </div>
            </div>
          ) : (
            <div className="p-12 text-center text-slate-400">
              <Receipt className="w-12 h-12 mx-auto mb-2 opacity-30" />
              <p className="text-xs">Pilih salah satu kwitansi untuk melihat detail dan mencetak.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
